### ISSUE TITLE
哪些行为会触发自动切换资源行为？

### ISSUE THREAD

**Issue by jsonchou** [bytelang/docs.kplayer.net#14]
Hi,

请问一下，哪些行为会触发自动切换资源行为？

更改config.json会自动触发吗，比如修改、增加、删除resource/list的条目或者顺序，或者删除cache等行为。

或者要手动调用命令触发？

文档中提到：

https://docs.kplayer.net/v0.5.8/option/overall.html

``` bash
./kplayer play start --config /xxx/kplayer/config2.json
```

执行之后，提示找不到文件，实际是存在的。
``` bash
FATA[2023-04-29 13:41:46] Config File "/xxx/kplayer/config2.json" Not Found in "[/xxx/kplayer]" 
```

首次运行，非常完美，想具体了解一下，切换资源的触发时机。

**Comment by vaptu** [comment]
```
./kplayer play start --config /xxx/kplayer/config2.json
```
用来手动指定配置文件的加载路径，以便于替换默认的配置文件寻找路径。

配置文件在首次加载完成之后不会持续监听配置文件中的资源改变，想要不重新执行程序的情况下修改播放方式可以通过kplayer提供的cli和api来控制播放行为

例如跳过当前播放的资源
cli
```
./kplayer play skip
```

api
```
curl -X "POST" "http://127.0.0.1:4156/play/skip" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{}'
```

目前cli和api暂未通过稳定性测试，可能在某些情况下会导致播放异常情况

**Comment by jsonchou** [comment]
@vaptu 

好的，感谢回复。

调用skip事件，读取的还是初始config中的resource/list，而非最新的config文件，对吗？

**Comment by vaptu** [comment]
是的，在首次加载完配置文件之后。在运行过程中不会二次更新配置文件
