### ISSUE TITLE
docker配置文件的运行命令有误

### ISSUE THREAD

**Issue by Cpu1998** [bytelang/docs.kplayer.net#17]
https://docs.kplayer.net/v0.5.8/helper/docker.html
官网中最后一个docker运行命令的name前面是中文的长横线（-），应该是两个英文的短横线（--）
原文命令：
sudo docker run -it —name kplayer \
 -v /video:/video \
 -v $PWD/config.json:/kplayer/config.json \
 bytelang/kplayer:latest

**Comment by vaptu** [comment]
谢谢，已更正
