### ISSUE TITLE
新版本0.5.7一些问题

### ISSUE THREAD

**Issue by diamond0422** [bytelang/docs.kplayer.net#2]
1、0.5.7版本是不是又去掉auth_on的配置项了，我看文档里没了；
2、外部程序调用的接口是http_port还是grpc_port呀，就是0.4.7的接口、0.5.6的rpc接口一样的；
3、下图里获取完整列表资源接口是get方式吗，-d参数可以传json_encode(array())吗，测试时一直返回connect to timed out超时；
![1](https://user-images.githubusercontent.com/45766642/193401429-008cf49a-f202-4485-96ed-eabf1e77720e.png)
4、queue模式不能跟0.4.7一样只保留1个并且可以循环吗= =!

**Comment by mvfeng** [comment]
...

**Comment by vaptu** [comment]
抱歉，在处理文档配置文件时遗漏了auth相关的入口，已添加。

外部程序通过http与grpc都可以和kplayer来进行通信，如果对grpc比较熟悉可以通过这里的 https://github.com/bytelang/libkplayer-proto 的proto文件来生成对应的编程语言的结构数据，它更加友好和安全。如果对http更加熟悉，推荐使用http接口

**Comment by vaptu** [comment]
```shell
curl "http://127.0.0.1:4156/resource/list-all" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{}'
```

在运行程序以后，测试过接口可以使用。请排查一下是不是开启了rpc功能并且http端口和示例中的4156端口一致。

返回结果是json，可以使用json反序列化的函数来解析它
