### ISSUE TITLE
关于kplayer2.0.0的cpu利用

### ISSUE THREAD

**Issue by def2u1t** [bytelang/docs.kplayer.net#4]
![8)6@4S SNESLXY3UDOS5@CS](https://user-images.githubusercontent.com/52809871/203943352-dae58f04-6056-471e-b7bb-9a52b34314ae.png)
如图所示，前期在使用kplayer进行推流时cpu的总利用率约在60-100之间，但是第二次推流后cpu利用直接上至160以上，以为是配置问题于是只开启了视频loop和缓存设置仍然没有得到问题解决

**Comment by def2u1t** [comment]
原来以为自己开多了kplayer cpu暴涨，播了有一会后又cpu又开始满载了，必须要关闭一下重启才能解决，再多修改了配置文件运行后，cpu又不行辣

**Comment by vaptu** [comment]
软件解码是比较计算密集，不同视频资源的质量和压缩程度也会导致CPU不是稳定在同一时刻的负载量。如果尝试使用缓存但无法降低CPU占用，请排查日志来判断缓存是不是正常生效。
在实际使用中，开启了缓存之后CPU可以大幅下降，可能是缓存配置错的缘故
