### ISSUE TITLE
部署异常

### ISSUE THREAD

**Issue by LIZEJU** [bytelang/docs.kplayer.net#6]
output add failed. error: I/O error [-5]      error="I/O error [-5]" path="rtmp://live-push.bilivideo.com/live-bvc/?

在本地虚拟机操作成功，但是在香港的vps上操作失败。

**Comment by vaptu** [comment]
bilibili目前是不允许非大陆ip进行推流的

**Comment by LIZEJU** [comment]
香港属于中国吗？香港的ip属于国内的ip吗。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月03日 13:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [bytelang/docs.kplayer.net] 部署异常 (Issue #6) |

bilibili目前是不允许非国内ip进行推流的

**Comment by vaptu** [comment]
> 香港属于中国吗？香港的ip属于国内的ip吗。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年01月03日 13:38 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [bytelang/docs.kplayer.net] 部署异常 (Issue #6) | bilibili目前是不允许非国内ip进行推流的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

笔误，已更正
